# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_QCOM_COMMAND_DB) += cmd-db.o
obj-$(CONFIG_QCOM_RPMH) += rpmh-rsc.o rpmh.o
obj-$(CONFIG_QCOM_ADSP_PAS) += qcom_adsp_pas.o
obj-$(CONFIG_QCOM_AOSS_QMP) += qcom_aoss_qmp.o
obj-$(CONFIG_QCOM_PMIC_GLINK) += pmic_glink.o
obj-$(CONFIG_QCOM_PMIC_GLINK_ALTMODE) += pmic_glink_altmode.o
obj-$(CONFIG_QCOM_PMIC_GLINK_UCSI) += pmic_glink_ucsi.o
obj-$(CONFIG_QCOM_PMIC_GLINK_BATTMGR) += pmic_glink_battmgr.o
