// SPDX-License-Identifier: GPL-2.0+
/*
 * ACPI Support for Particle Tachyon (QCM6490)
 * 
 * MADT (GICC/GICD/GICR/ITS) is generated via U-Boot's driver model:
 *   - armv8_cpu driver: fills GICC entries per CPU
 *   - arm_gic_v3 driver: fills GICD + GICR entries
 *   - arm_gic_v3_its driver: fills the ITS entry
 * 
 * Board-specific tables (FADT, IORT, PPTT, DSDT, CSRT, MCFG, TPM2)
 * remain as custom writers here.
 *
 * Based on the extracted ACPI tables from FAT12.bin
 *
 * Copyright (c) 2024-2025 Particle Industries, Inc.
 */

#include <cpu.h>
#include <tables_csum.h>
#include <string.h>
#include <acpi/acpi_table.h>
#include <asm/acpi_table.h>
#include <asm/armv8/sec_firmware.h>
#include <dm/uclass.h>
#include <dm/device.h>

/*
 * QCM6490 SoC ACPI Support for Windows ARM64 boot
 *
 * PSCI is handled by TF-A (Trusted Firmware-A) at EL3.
 * U-Boot's role is to:
 * 1. Declare PSCI compliance in FADT (arm_boot_arch field)
 * 2. Provide correct ACPI tables so Windows can boot and use SMP
 *
 * MADT sub-table generation uses the driver model:
 *   - CPU driver (armv8_cpu.c, compatible "qcom,kryo"): GICC entries
 *   - GICv3 driver (gic-v3-its.c, compatible "arm,gic-v3"): GICD + GICR
 *   - GICv3 ITS driver (compatible "arm,gic-v3-its"): ITS entry
 */

void acpi_fill_fadt(struct acpi_fadt *fadt)
{
	/*
	 * Set FADT fields for ARM64 ACPI:
	 *
	 * FADT Flags (offset 112):
	 * - ACPI_FADT_HW_REDUCED_ACPI (bit 20): Required for ARM (no legacy hardware)
	 * - ACPI_FADT_LOW_PWR_IDLE_S0 (bit 21): Support for S0 low power idle
	 */
	fadt->flags = ACPI_FADT_HW_REDUCED_ACPI | ACPI_FADT_LOW_PWR_IDLE_S0;

	/*
	 * ARM Boot Architecture Flags (offset 244):
	 * - ACPI_ARM_PSCI_COMPLIANT (bit 0): Tells Windows that PSCI is
	 *   available for CPU bring-up (SMP support)
	 *
	 * Note: The actual PSCI implementation runs in TF-A at EL3.
	 * U-Boot just needs to declare compliance here.
	 */
	fadt->arm_boot_arch = ACPI_ARM_PSCI_COMPLIANT;

	/*
	 * Set preferred power management profile for embedded/IoT device
	 * ACPI_PM_MOBILE = 2 (mobile/embedded device)
	 */
	fadt->preferred_pm_profile = ACPI_PM_MOBILE;

	/*
	 * Set FADT revision to 6 (ACPI 6.0+)
	 * This is required for ARM64 support
	 */
	fadt->header.revision = ACPI_FADT_REV_ACPI_6_0;
}

/*
 * IORT (IO Remapping Table) support — REQUIRED for Qualcomm Windows boot
 *
 * Describes the SMMU (System MMU) and GIC ITS topology so Windows can
 * correctly configure DMA remapping and MSI interrupt translation.
 *
 * QCM6490 (SC7280) IORT topology:
 *   ITS Group (GIC ITS @ 0x17a40000, ID 0)
 *     └── SMMUv2 (ARM MMU-500 @ 0x15000000)
 *           └── PCIe Root Complex (segment 0, bus 0-255)
 *
 * Without this table:
 * - Windows may fail to boot or use polled I/O
 * - DMA from PCIe/Storage may not work correctly
 * - MSI/MSI-X interrupts may not be delivered
 */
int acpi_fill_iort(struct acpi_ctx *ctx)
{
	u32 its_offset, smmu_offset;

	/*
	 * GIC ITS (Interrupt Translation Service) Group node
	 *
	 * Type: 0x00 (ITS Group)
	 * ITS ID: 0 — must match the gic_its_id field of the MADT GIC ITS entry
	 *         (type 0x0F) generated by the arm_gic_v3_its driver.
	 *
	 * Windows uses this to discover which ITS provides MSI translation
	 * for the SMMU's own control interrupts.
	 */
	u32 identifiers[] = { 0 };

	its_offset = acpi_iort_add_its_group(ctx, ARRAY_SIZE(identifiers),
					     identifiers);

	/*
	 * SMMUv2 (ARM MMU-500) node
	 *
	 * Type: 0x03 (SMMU)
	 * Base: 0x15000000 — apps_smmu from sc7280.dtsi
	 * Size: 0x100000 (1MB — same as DT reg size)
	 * Model: 0 (generic MMU-500)
	 *
	 * Interrupts (from sc7280.dtsi apps_smmu node):
	 * - Global interrupt: GIC_SPI 65 (level-high, #global-interrupts=1)
	 * - Context interrupts: pre-configured by hypervisor, not listed here
	 *   (SMMU is in bypass for all streams under Gunyah hyp)
	 *
	 * Flags: COHERENT_WALK — SMMU page table walks are cache-coherent
	 *        (matches dma-coherent property in DT)
	 *
	 * ID mapping: SMMU control interrupts → ITS Group (offset its_offset)
	 *             Input range 0-0xFFFF (all SIDs)
	 */
	u32 global_gsiv[4] = { 65, 0, 0, 0 };
	u32 global_flags[4] = { 0, 0, 0, 0 };  /* 0 = level-triggered */

	struct acpi_iort_id_mapping map_smmu[] = {{
		0,           /* input_base: lowest StreamID to match */
		0xffff,      /* id_count: number of StreamIDs */
		0,           /* output_base: lowest output ID */
		its_offset,  /* output_reference: offset to ITS Group node */
		0            /* flags: single-mapping = 0 (range mapping) */
	}};

	smmu_offset = acpi_iort_add_smmu(ctx,
		0x15000000,                 /* base_address (apps_smmu) */
		0x100000,                   /* span (1MB register space) */
		0,                          /* model (generic MMU-500) */
		ACPI_IORT_SMMU_COHERENT_WALK, /* flags (dma-coherent) */
		global_gsiv,                /* global interrupt GSIVs */
		global_flags,               /* global interrupt flags */
		0,                          /* num_ctx_irq (none — hyp owns) */
		NULL,                       /* ctx_irq array */
		0,                          /* num_pmu_irq (none) */
		NULL,                       /* pmu_irq array */
		ARRAY_SIZE(map_smmu),       /* num_mappings */
		map_smmu);                  /* ID mapping array */

	/*
	 * PCIe Root Complex node
	 *
	 * Type: 0x02 (PCI Root Complex)
	 * Segment: 0 (matches MCFG pci_segment_group_number = 0)
	 * Memory address size limit: 64 (64-bit addressing)
	 *
	 * Memory access properties:
	 *   bit 0  = Cache Coherent (PCIe is cache-coherent on this SoC)
	 *   bit 56 = CCA/CPM (Coherent Processing Memory — ARM-specific)
	 *
	 * ID mapping: PCIe Requester ID → SMMU (offset smmu_offset)
	 *             Input range 0-0xFFFF covers all 16-bit RIDs
	 */
	struct acpi_iort_id_mapping map_rc[] = {{
		0,            /* input_base: lowest RequesterID */
		0xffff,       /* id_count: number of RequesterIDs */
		0,            /* output_base: lowest SMMU StreamID */
		smmu_offset,  /* output_reference: offset to SMMU node */
		0             /* flags: single-mapping = 0 (range mapping) */
	}};

	acpi_iort_add_rc(ctx,
		BIT(0) | BIT(56),       /* mem_access_properties (CacheCoherent + CPM) */
		0,                      /* ats_attributes (ATS not supported) */
		0,                      /* pci_segment_number (matches MCFG) */
		64,                     /* memory_address_size_limit (64-bit) */
		ARRAY_SIZE(map_rc),     /* num_mappings */
		map_rc);                /* ID mapping array */

	return 0;
}

/*
 * PPTT (Processor Properties Topology Table) support
 * Defines CPU/cache topology for Windows
 */
static int tachyon_write_pptt(struct acpi_ctx *ctx, const struct acpi_writer *entry)
{
	struct acpi_table_header *header;
	u32 l1_offsets[8], l2_offsets[8];
	u32 l3_offset, l2_offset, cluster_offset;

	header = ctx->current;
	ctx->tab_start = ctx->current;

	memset(header, 0, sizeof(struct acpi_table_header));

	acpi_fill_header(header, "PPTT");
	header->revision = acpi_get_table_revision(ACPITAB_PPTT);
	acpi_inc(ctx, sizeof(*header));

	/*
	 * Define cache topology for QCM6490 (SC7280):
	 * - L1i and L1d per CPU (32KB each)
	 * - L2 per cluster (512KB per cluster)
	 * - L3 shared by all CPUs (4MB)
	 */

	/* L3 Cache - shared by all 8 CPUs */
	l3_offset = acpi_pptt_add_cache(ctx,
		ACPI_PPTT_ALL_VALID, 0,
		0x400000,  /* 4MB L3 cache */
		0x800,    /* Number of sets */
		16,       /* Associativity (16-way) */
		ACPI_PPTT_READ_ALLOC | ACPI_PPTT_WRITE_ALLOC |
		(ACPI_PPTT_CACHE_TYPE_UNIFIED << ACPI_PPTT_CACHE_TYPE_SHIFT),
		64);      /* Cache line size */

	/* L2 Cache - per cluster (512KB) */
	l2_offset = acpi_pptt_add_cache(ctx,
		ACPI_PPTT_ALL_VALID, 0,
		0x80000,  /* 512KB L2 per cluster */
		0x400,    /* Number of sets */
		8,        /* Associativity (8-way) */
		ACPI_PPTT_READ_ALLOC | ACPI_PPTT_WRITE_ALLOC |
		(ACPI_PPTT_CACHE_TYPE_UNIFIED << ACPI_PPTT_CACHE_TYPE_SHIFT),
		64);

	/* Cluster node (contains L2 cache) */
	cluster_offset = acpi_pptt_add_proc(ctx,
		ACPI_PPTT_PHYSICAL_PACKAGE |
		ACPI_PPTT_CHILDREN_IDENTICAL,
		0, 0, 1, &l2_offset);

	/* L1 Data Cache - 32KB per CPU */
	for (int i = 0; i < 8; i++) {
		l1_offsets[i] = acpi_pptt_add_cache(ctx,
			ACPI_PPTT_ALL_VALID, 0,
			0x8000,   /* 32KB L1d */
			0x100,    /* Number of sets */
			2,        /* Associativity (2-way) */
			ACPI_PPTT_READ_ALLOC | ACPI_PPTT_WRITE_ALLOC |
			(ACPI_PPTT_CACHE_TYPE_DATA << ACPI_PPTT_CACHE_TYPE_SHIFT),
			64);
	}

	/* L1 Instruction Cache - 32KB per CPU */
	for (int i = 0; i < 8; i++) {
		l2_offsets[i] = acpi_pptt_add_cache(ctx,
			ACPI_PPTT_ALL_BUT_WRITE_POL, 0,
			0x8000,   /* 32KB L1i */
			0x100,    /* Number of sets */
			2,        /* Associativity (2-way) */
			ACPI_PPTT_READ_ALLOC |
			(ACPI_PPTT_CACHE_TYPE_INSTR << ACPI_PPTT_CACHE_TYPE_SHIFT),
			64);
	}

	/* CPU nodes - leaf nodes with L1 caches */
	for (int i = 0; i < 8; i++) {
		u32 caches[2] = { l1_offsets[i], l2_offsets[i] };
		acpi_pptt_add_proc(ctx,
			ACPI_PPTT_CHILDREN_IDENTICAL |
			ACPI_PPTT_NODE_IS_LEAF |
			ACPI_PPTT_PROC_ID_VALID,
			cluster_offset, i, 2, caches);
	}

	header->length = ctx->current - ctx->tab_start;
	header->checksum = table_compute_checksum(header, header->length);

	acpi_inc(ctx, header->length);
	acpi_add_table(ctx, header);

	return 0;
}

ACPI_WRITER(5pptt, "PPTT", tachyon_write_pptt, 0);

/*
 * GTDT (Generic Timer Description Table) support
 * ARM Generic Timer interrupts for Windows
 */
static int tachyon_write_gtdt(struct acpi_ctx *ctx, const struct acpi_writer *entry)
{
	struct acpi_table_header *header;
	struct acpi_gtdt *gtdt;

	gtdt = ctx->current;
	header = &gtdt->header;

	memset(gtdt, 0, sizeof(struct acpi_gtdt));

	acpi_fill_header(header, "GTDT");
	header->length = sizeof(struct acpi_gtdt);
	header->revision = acpi_get_table_revision(ACPITAB_GTDT);

	/*
	 * ARM Generic Timer interrupts (PPI - Private Peripheral Interrupts)
	 * These match the device tree timer node interrupts:
	 * - Secure EL1 timer: PPI 29
	 * - Non-secure EL1 timer: PPI 30
	 * - Virtual EL1 timer: PPI 27
	 * - EL2 timer: PPI 26
	 *
	 * Note: The extracted table had these as 0. We use the correct values.
	 */
	gtdt->cnt_ctrl_base = 0xFFFFFFFFFFFFFFFF; /* Not used */
	gtdt->sec_el1_gsiv = 29;  /* Secure EL1 timer */
	gtdt->sec_el1_flags = GTDT_FLAG_INT_ACTIVE_LOW;
	gtdt->el1_gsiv = 30;      /* Non-secure EL1 timer */
	gtdt->el1_flags = GTDT_FLAG_INT_ACTIVE_LOW;
	gtdt->virt_el1_gsiv = 27; /* Virtual EL1 timer */
	gtdt->virt_el1_flags = GTDT_FLAG_INT_ACTIVE_LOW;
	gtdt->el2_gsiv = 26;      /* EL2 timer */
	gtdt->el2_flags = GTDT_FLAG_INT_ACTIVE_LOW;
	gtdt->cnt_read_base = 0xFFFFFFFFFFFFFFFF;

	header->checksum = table_compute_checksum(header, header->length);

	acpi_add_table(ctx, gtdt);
	acpi_inc(ctx, sizeof(struct acpi_gtdt));

	return 0;
}

ACPI_WRITER(5gtdt, "GTDT", tachyon_write_gtdt, 0);

/*
 * MCFG (PCI Express MMIO Config Space) support
 * ECAM for PCIe controllers
 *
 * The generic ACPI code already registers an MCFG writer
 * (lib/acpi/mcfg.c: ACPI_WRITER(5mcfg, "MCFG", acpi_write_mcfg, 0)).
 * That writer calls the weak acpi_fill_mcfg() to append MMConfig
 * entries.  We implement that hook here so we don't create a
 * duplicate linker-list entry with the same name.
 */
int acpi_fill_mcfg(struct acpi_ctx *ctx)
{
	/*
	 * PCIe ECAM (Enhanced Configuration Access Mechanism)
	 * Base: 0x40000000 (from extracted table)
	 * Segment: 0
	 * Start Bus: 0
	 * End Bus: 255 (full bus range)
	 */
	acpi_create_mcfg_mmconfig(ctx->current,
		0x40000000,  /* ECAM base from extracted table */
		0,           /* PCI segment group number */
		0,           /* Start bus number */
		255);         /* End bus number */

	acpi_inc(ctx, sizeof(struct acpi_mcfg_mmconfig));
	return 0;
}

/*
 * BGRT (Boot Graphics Resource Table) support
 * Shows OEM logo during boot
 */
static int tachyon_write_bgrt(struct acpi_ctx *ctx, const struct acpi_writer *entry)
{
	struct acpi_table_header *header;

	header = ctx->current;

	acpi_fill_header(header, "BGRT");
	header->length = sizeof(struct acpi_bgrt);
	header->revision = acpi_get_table_revision(ACPITAB_BGRT);

	/* BGRT: Version 1, Status 0 (displayed), Image type 0 (BMP) */
	struct acpi_bgrt *bgrt = (struct acpi_bgrt *)header;
	bgrt->version = 1;
	bgrt->status = 0;  /* Image displayed */
	bgrt->image_type = 0;  /* BMP format */
	bgrt->offset_x = 0;
	bgrt->offset_y = 0;
	/* image_address is set by firmware if logo is present */

	header->checksum = table_compute_checksum(header, header->length);

	acpi_add_table(ctx, header);
	acpi_inc(ctx, sizeof(struct acpi_bgrt));

	return 0;
}

ACPI_WRITER(5bgrt, "BGRT", tachyon_write_bgrt, 0);

/*
 * DBG2 (Debug Port Table 2) support
 * Defines debug UART for Windows debugging
 */
static int tachyon_write_dbg2(struct acpi_ctx *ctx, const struct acpi_writer *entry)
{
	struct acpi_table_header *header;
	struct acpi_dbg2_device *dbg2;
	u32 *addr_size;

	header = ctx->current;

	acpi_fill_header(header, "DBG2");
	header->length = sizeof(struct acpi_dbg2_header) + sizeof(struct acpi_dbg2_device) + 16;
	header->revision = 0;  /* DBG2 revision 0 */

	/* DBG2 header */
	struct acpi_dbg2_header *dbg2_hdr = (struct acpi_dbg2_header *)header;
	dbg2_hdr->devices_offset = sizeof(struct acpi_dbg2_header);
	dbg2_hdr->devices_count = 1;

	/* DBG2 device (UART5 - debug console) */
	dbg2 = (struct acpi_dbg2_device *)((void *)header + sizeof(struct acpi_dbg2_header));
	dbg2->revision = 0;
	dbg2->length = sizeof(struct acpi_dbg2_device) + 16;
	dbg2->address_count = 1;
	dbg2->namespace_string_length = 4;
	dbg2->namespace_string_offset = dbg2->length;
	dbg2->oem_data_length = 0;
	dbg2->oem_data_offset = dbg2->length + dbg2->namespace_string_length;
	dbg2->port_type = ACPI_DBG2_ARM_SBSA_32BIT;
	dbg2->port_subtype = ACPI_DBG2_ARM_SBSA_GENERIC;
	dbg2->reserved = 0;

	/* Namespace string: "\_SB_.UART5" */
	char *ns = (char *)dbg2 + dbg2->namespace_string_offset;
	memcpy(ns, "\\_SB.UART5", 10);

	/* Address (GICC base from device tree) */
	addr_size = (u32 *)((void *)dbg2 + dbg2->length);
	addr_size[0] = 0x994000;  /* UART5 base from qcm6490-tachyon-u-boot.dtsi */
	addr_size[1] = 0;      /* Base address high */
	addr_size[2] = 0x1000;  /* Address size */
	addr_size[3] = 0x1000;  /* Size of address region */

	header->checksum = table_compute_checksum(header, header->length);

	acpi_add_table(ctx, header);
	acpi_inc(ctx, header->length);

	return 0;
}

ACPI_WRITER(5dbg2, "DBG2", tachyon_write_dbg2, 0);

/*
 * SPCR (Serial Port Console Redirection) support
 *
 * The generic ACPI code already registers an SPCR writer
 * (lib/acpi/acpi_table.c: ACPI_WRITER(5spcr, "SPCR", acpi_write_spcr, 0)).
 * It auto-discovers the serial device via driver model (gd->cur_serial_dev).
 * We do NOT create a second 5spcr writer — duplicate linker-list names
 * are not safe.  If the auto-discovered values don't match the target
 * hardware, fix the serial driver's .getinfo() / .getconfig() callbacks
 * or the device tree, not the SPCR table itself.
 */

/*
 * FACS (Firmware ACPI Control Structure)
 *
 * The generic ACPI code already writes FACS at writer priority 1
 * (lib/acpi/facs.c: ACPI_WRITER(1facs, "FACS", acpi_write_facs, 0))
 * and stores it in ctx->facs for FADT to reference.
 *
 * FACS is NOT listed as a normal XSDT table — it is pointed to by
 * the FADT firmware_ctrl / x_firmware_ctrl fields.  Publishing a
 * second FACS via acpi_add_table() is incorrect per the ACPI spec.
 * We therefore remove the custom Tachyon FACS writer entirely.
 */

/*
 * TPM2 (Trusted Platform Module 2.0) Table
 * Required by Windows 11 to discover the firmware TPM (fTPM in OP-TEE)
 *
 * Uses start_method = 7 (Command Response Buffer) for fTPM over TEE.
 * The EFI TCG2 protocol manages its own event log; we reference the
 * log buffer that EFI TCG2 will allocate.
 */
static int tachyon_write_tpm2(struct acpi_ctx *ctx, const struct acpi_writer *entry)
{
	struct acpi_table_header *header;
	struct acpi_tpm2 *tpm2;

	if (!IS_ENABLED(CONFIG_TPM_V2))
		return -ENOENT;

	tpm2 = ctx->current;
	header = &tpm2->header;
	memset(tpm2, 0, sizeof(struct acpi_tpm2));

	acpi_fill_header(header, "TPM2");
	header->length = sizeof(struct acpi_tpm2);
	header->revision = acpi_get_table_revision(ACPITAB_TPM2);

	/* Platform class: 1 = client system */
	tpm2->platform_class = 1;

	/*
	 * Start method 7 = Command Response Buffer
	 * This is the correct method for fTPM running in OP-TEE,
	 * where the OS communicates via SMC calls through the
	 * TCG2 protocol rather than direct MMIO.
	 */
	tpm2->control_area = 0;
	tpm2->start_method = 7;
	memset(tpm2->msp, 0, sizeof(tpm2->msp));

	/*
	 * Log Area Minimum Length (laml) and Log Area Start Address (lasa):
	 * The EFI TCG2 protocol allocates its own event log buffer at boot.
	 * Set laml to the configured log size; lasa will be populated by
	 * the EFI TCG2 protocol at ExitBootServices or left zero if not
	 * yet available.
	 */
	tpm2->laml = CONFIG_TPM2_EVENT_LOG_SIZE;
	tpm2->lasa = 0;

	header->checksum = table_compute_checksum(tpm2, header->length);

	acpi_inc(ctx, tpm2->header.length);
	acpi_add_table(ctx, tpm2);

	return 0;
}

ACPI_WRITER(5tpm2, "TPM2", tachyon_write_tpm2, 0);
